Repository fungover/thunder, pull requests merged in 2024-02, with the labels that each got.

#2 Convention for github
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#3 Thunder CI pipline
  .github/workflows/maven.yml
  pom.xml
Labels: devops

#13 Add server on port 1883 and a way to handle incoming connections
  src/main/java/org/fungover/Main.java
  src/main/java/org/fungover/thunder/ClientHandler.java
  src/main/java/org/fungover/thunder/Main.java
  src/main/java/org/fungover/thunder/Server.java
Labels: enhancement

#11 deleted top level metadata which responsible for labels titles and as…
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#7 add README.md
  README.md
Labels: documentation

#35 Add dependency for Mockito
  pom.xml
Labels: bug

#20 Editorconfig
  .editorconfig
Labels: devops

#41 Remove duplicate dependencies tag
  pom.xml
Labels: bug, Critical Bug

#45 CD Automated Delivery
  .github/release-drafter.config.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: devops

#42 18 handling disconnect
  src/main/java/org/fungover/thunder/ClientHandler.java
  src/main/java/org/fungover/thunder/PackageReader.java
  src/test/java/org/fungover/thunder/ClientHandlerTest.java
  src/test/java/org/fungover/thunder/PackageReaderTest.java
Labels: enhancement

#48 reverted back deleted changes
  .github/workflows/release.yml
Labels: devops, critical bug

#49 added s to action
  .github/workflows/release.yml
Labels: devops, critical bug

#29 14 topics handler
  src/main/java/org/fungover/thunder/Topic.java
  src/test/java/org/fungover/thunder/TopicTest.java
Labels: enhancement

#57 55-bug-format-project
  src/main/java/org/fungover/thunder/ClientHandler.java
  src/main/java/org/fungover/thunder/Main.java
  src/main/java/org/fungover/thunder/PackageReader.java
  src/main/java/org/fungover/thunder/Topic.java
  src/test/java/org/fungover/thunder/ClientHandlerTest.java
  src/test/java/org/fungover/thunder/PackageReaderTest.java
  src/test/java/org/fungover/thunder/TopicTest.java
Labels: minor

#43 40 create client class
  src/main/java/org/fungover/thunder/Client.java
  src/main/java/org/fungover/thunder/ClientHandler.java
  src/main/java/org/fungover/thunder/Main.java
  src/test/java/org/fungover/thunder/.gitkeep
  src/test/java/org/fungover/thunder/ClientTest.java
Labels: enhancement

#59 Update maven.yml
  .github/workflows/maven.yml
Labels: devops

#58 25 feature subscribe to topic
  src/main/java/org/fungover/thunder/ClientHandler.java
  src/main/java/org/fungover/thunder/PackageReader.java
  src/main/java/org/fungover/thunder/Subscription.java
  src/main/java/org/fungover/thunder/Topic.java
  src/test/java/org/fungover/thunder/PackageReaderTest.java
  src/test/java/org/fungover/thunder/SubscriptionTest.java
  src/test/java/org/fungover/thunder/TopicTest.java
Labels: enhancement, minor
